name: Deploy / Ship

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Release
    types:
      - completed

jobs:
  vscode-marketplace:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Placeholder
        run: echo "VS Code Marketplace ship workflow placeholder"
